name: Book micro-service's ci/cd workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: setup JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: 'adopt'
          cache: maven
      - name: build with maven
        run: mvn clean install
      - name: build and push docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: sachinkumarbsde/books-service
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
